-- Generated by generate_core_data.py from the frozen selected cell.
-- Definitions only: all containment and exclusion claims are proved separately.
import Mathlib.Basic.Real.Basic
import Mathlib.Data.Fin.VecNotation

namespace SixTrianglePilot.CoreData
noncomputable section

def referenceVertices : Fin 3 → Fin 2 → ℝ := ![![(-1 / 3 : ℝ), (-1 / 3 : ℝ)], ![(2 / 3 : ℝ), (-1 / 3 : ℝ)], ![(-1 / 3 : ℝ), (2 / 3 : ℝ)]]

def core0 : Fin 3 → Fin 2 → ℝ := ![![(-43705621 / 67112961 : ℝ), (21338603 / 67112961 : ℝ)], ![(22367018 / 67112961 : ℝ), (-43705621 / 67112961 : ℝ)], ![(21338603 / 67112961 : ℝ), (22367018 / 67112961 : ℝ)]]
def core1 : Fin 3 → Fin 2 → ℝ := core0
def core2 : Fin 3 → Fin 2 → ℝ := ![![(-10589021 / 16278153 : ℝ), (4917667 / 16278153 : ℝ)], ![(5671354 / 16278153 : ℝ), (-10589021 / 16278153 : ℝ)], ![(4917667 / 16278153 : ℝ), (5671354 / 16278153 : ℝ)]]

def core : Fin 3 → Fin 3 → Fin 2 → ℝ := ![core0, core1, core2]
def lower : Fin 3 → ℝ := ![(-1 / 3 : ℝ), (-1 / 3 : ℝ), (-31 / 96 : ℝ)]
def upper : Fin 3 → ℝ := ![(-31 / 96 : ℝ), (-31 / 96 : ℝ), (-5 / 16 : ℝ)]
def frames : Fin 3 → ℝ := ![(-21 / 64 : ℝ), (-21 / 64 : ℝ), (-61 / 192 : ℝ)]
def scales : Fin 3 → ℝ := ![(21854827 / 22370987 : ℝ), (21854827 / 22370987 : ℝ), (5298979 / 5426051 : ℝ)]

end
end SixTrianglePilot.CoreData
