-- Generated by generate_core_facets.py; every certificate field is proved in Lean.
import Pilot.Radial
import Pilot.CoreData
import Pilot.SelectedGeometry

set_option maxRecDepth 4096
set_option maxHeartbeats 2000000

namespace SixTrianglePilot.CoreSeparation
noncomputable section
open CoreData Selected Polygon Geometry

def normals00 : Fin 6 → Fin 2 → ℝ := ![![(-5461 : ℝ), (-85 : ℝ)], ![(-5376 : ℝ), (-5461 : ℝ)], ![(85 : ℝ), (-5376 : ℝ)], ![(5461 : ℝ), (85 : ℝ)], ![(5376 : ℝ), (5461 : ℝ)], ![(-85 : ℝ), (5376 : ℝ)]]
def thresholds00 : Fin 6 → ℝ := ![(118431307513 / 22370987 : ℝ), (118431307513 / 22370987 : ℝ), (118431307513 / 22370987 : ℝ), (118431307513 / 22370987 : ℝ), (118431307513 / 22370987 : ℝ), (118431307513 / 22370987 : ℝ)]

def certificate00 : RadialCertificate core0 core0 where
  normal := normals00
  threshold := thresholds00
  threshold_pos k := by
    fin_cases k <;> norm_num [thresholds00]
  positive_support d hd := by
    by_contra! h
    have h1 := h 1
    have h3 := h 3
    have h5 := h 5
    simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at h1 h3 h5
    change (-5376 : ℝ) * d 0 + (-5461 : ℝ) * d 1 ≤ 0 at h1
    change (5461 : ℝ) * d 0 + (85 : ℝ) * d 1 ≤ 0 at h3
    change (-85 : ℝ) * d 0 + (5376 : ℝ) * d 1 ≤ 0 at h5
    have hx : d 0 = 0 := by apply le_antisymm <;> linarith
    have hy : d 1 = 0 := by apply le_antisymm <;> linarith
    apply hd
    ext i
    fin_cases i
    · exact hx
    · exact hy
  boundary_decomposition k d heq hall := by
    fin_cases k
    · have hp := hall 5
      have hn := hall 1
      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn
      change (-5461 : ℝ) * d 0 + (-85 : ℝ) * d 1 = (118431307513 / 22370987 : ℝ) at heq
      change (-85 : ℝ) * d 0 + (5376 : ℝ) * d 1 ≤ (118431307513 / 22370987 : ℝ) at hp
      change (-5376 : ℝ) * d 0 + (-5461 : ℝ) * d 1 ≤ (118431307513 / 22370987 : ℝ) at hn
      let t : ℝ := (-22370987 / 22024213 : ℝ) * d 1 + (5376 / 5461 : ℝ)
      have ht0 : 0 ≤ t := by dsimp [t]; linarith
      have ht1 : t ≤ 1 := by dsimp [t]; linarith
      refine ⟨(1-t) • core0 0 + t • core0 0, ?_,
        (1-t) • core0 1 + t • core0 2, ?_, ?_⟩
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (by linarith) ht0 (by ring)
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (by linarith) ht0 (by ring)
      · ext axis
        fin_cases axis
        · change d 0 = ((1-t)*(-43705621 / 67112961 : ℝ) + t*(-43705621 / 67112961 : ℝ)) -
            ((1-t)*(22367018 / 67112961 : ℝ) + t*(21338603 / 67112961 : ℝ))
          dsimp [t]
          linarith
        · change d 1 = ((1-t)*(21338603 / 67112961 : ℝ) + t*(21338603 / 67112961 : ℝ)) -
            ((1-t)*(-43705621 / 67112961 : ℝ) + t*(22367018 / 67112961 : ℝ))
          dsimp [t]
          linarith
    · have hp := hall 0
      have hn := hall 2
      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn
      change (-5376 : ℝ) * d 0 + (-5461 : ℝ) * d 1 = (118431307513 / 22370987 : ℝ) at heq
      change (-5461 : ℝ) * d 0 + (-85 : ℝ) * d 1 ≤ (118431307513 / 22370987 : ℝ) at hp
      change (85 : ℝ) * d 0 + (-5376 : ℝ) * d 1 ≤ (118431307513 / 22370987 : ℝ) at hn
      let t : ℝ := (22370987 / 22024213 : ℝ) * d 0 + (5376 / 5461 : ℝ)
      have ht0 : 0 ≤ t := by dsimp [t]; linarith
      have ht1 : t ≤ 1 := by dsimp [t]; linarith
      refine ⟨(1-t) • core0 0 + t • core0 1, ?_,
        (1-t) • core0 2 + t • core0 2, ?_, ?_⟩
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (by linarith) ht0 (by ring)
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (by linarith) ht0 (by ring)
      · ext axis
        fin_cases axis
        · change d 0 = ((1-t)*(-43705621 / 67112961 : ℝ) + t*(22367018 / 67112961 : ℝ)) -
            ((1-t)*(21338603 / 67112961 : ℝ) + t*(21338603 / 67112961 : ℝ))
          dsimp [t]
          linarith
        · change d 1 = ((1-t)*(21338603 / 67112961 : ℝ) + t*(-43705621 / 67112961 : ℝ)) -
            ((1-t)*(22367018 / 67112961 : ℝ) + t*(22367018 / 67112961 : ℝ))
          dsimp [t]
          linarith
    · have hp := hall 1
      have hn := hall 3
      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn
      change (85 : ℝ) * d 0 + (-5376 : ℝ) * d 1 = (118431307513 / 22370987 : ℝ) at heq
      change (-5376 : ℝ) * d 0 + (-5461 : ℝ) * d 1 ≤ (118431307513 / 22370987 : ℝ) at hp
      change (5461 : ℝ) * d 0 + (85 : ℝ) * d 1 ≤ (118431307513 / 22370987 : ℝ) at hn
      let t : ℝ := (22370987 / 21681408 : ℝ) * d 0 + (-85 / 5376 : ℝ)
      have ht0 : 0 ≤ t := by dsimp [t]; linarith
      have ht1 : t ≤ 1 := by dsimp [t]; linarith
      refine ⟨(1-t) • core0 1 + t • core0 1, ?_,
        (1-t) • core0 2 + t • core0 0, ?_, ?_⟩
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (by linarith) ht0 (by ring)
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (by linarith) ht0 (by ring)
      · ext axis
        fin_cases axis
        · change d 0 = ((1-t)*(22367018 / 67112961 : ℝ) + t*(22367018 / 67112961 : ℝ)) -
            ((1-t)*(21338603 / 67112961 : ℝ) + t*(-43705621 / 67112961 : ℝ))
          dsimp [t]
          linarith
        · change d 1 = ((1-t)*(-43705621 / 67112961 : ℝ) + t*(-43705621 / 67112961 : ℝ)) -
            ((1-t)*(22367018 / 67112961 : ℝ) + t*(21338603 / 67112961 : ℝ))
          dsimp [t]
          linarith
    · have hp := hall 2
      have hn := hall 4
      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn
      change (5461 : ℝ) * d 0 + (85 : ℝ) * d 1 = (118431307513 / 22370987 : ℝ) at heq
      change (85 : ℝ) * d 0 + (-5376 : ℝ) * d 1 ≤ (118431307513 / 22370987 : ℝ) at hp
      change (5376 : ℝ) * d 0 + (5461 : ℝ) * d 1 ≤ (118431307513 / 22370987 : ℝ) at hn
      let t : ℝ := (22370987 / 22024213 : ℝ) * d 1 + (5376 / 5461 : ℝ)
      have ht0 : 0 ≤ t := by dsimp [t]; linarith
      have ht1 : t ≤ 1 := by dsimp [t]; linarith
      refine ⟨(1-t) • core0 1 + t • core0 2, ?_,
        (1-t) • core0 0 + t • core0 0, ?_, ?_⟩
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (by linarith) ht0 (by ring)
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (by linarith) ht0 (by ring)
      · ext axis
        fin_cases axis
        · change d 0 = ((1-t)*(22367018 / 67112961 : ℝ) + t*(21338603 / 67112961 : ℝ)) -
            ((1-t)*(-43705621 / 67112961 : ℝ) + t*(-43705621 / 67112961 : ℝ))
          dsimp [t]
          linarith
        · change d 1 = ((1-t)*(-43705621 / 67112961 : ℝ) + t*(22367018 / 67112961 : ℝ)) -
            ((1-t)*(21338603 / 67112961 : ℝ) + t*(21338603 / 67112961 : ℝ))
          dsimp [t]
          linarith
    · have hp := hall 3
      have hn := hall 5
      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn
      change (5376 : ℝ) * d 0 + (5461 : ℝ) * d 1 = (118431307513 / 22370987 : ℝ) at heq
      change (5461 : ℝ) * d 0 + (85 : ℝ) * d 1 ≤ (118431307513 / 22370987 : ℝ) at hp
      change (-85 : ℝ) * d 0 + (5376 : ℝ) * d 1 ≤ (118431307513 / 22370987 : ℝ) at hn
      let t : ℝ := (-22370987 / 22024213 : ℝ) * d 0 + (5376 / 5461 : ℝ)
      have ht0 : 0 ≤ t := by dsimp [t]; linarith
      have ht1 : t ≤ 1 := by dsimp [t]; linarith
      refine ⟨(1-t) • core0 2 + t • core0 2, ?_,
        (1-t) • core0 0 + t • core0 1, ?_, ?_⟩
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (by linarith) ht0 (by ring)
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (by linarith) ht0 (by ring)
      · ext axis
        fin_cases axis
        · change d 0 = ((1-t)*(21338603 / 67112961 : ℝ) + t*(21338603 / 67112961 : ℝ)) -
            ((1-t)*(-43705621 / 67112961 : ℝ) + t*(22367018 / 67112961 : ℝ))
          dsimp [t]
          linarith
        · change d 1 = ((1-t)*(22367018 / 67112961 : ℝ) + t*(22367018 / 67112961 : ℝ)) -
            ((1-t)*(21338603 / 67112961 : ℝ) + t*(-43705621 / 67112961 : ℝ))
          dsimp [t]
          linarith
    · have hp := hall 4
      have hn := hall 0
      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn
      change (-85 : ℝ) * d 0 + (5376 : ℝ) * d 1 = (118431307513 / 22370987 : ℝ) at heq
      change (5376 : ℝ) * d 0 + (5461 : ℝ) * d 1 ≤ (118431307513 / 22370987 : ℝ) at hp
      change (-5461 : ℝ) * d 0 + (-85 : ℝ) * d 1 ≤ (118431307513 / 22370987 : ℝ) at hn
      let t : ℝ := (-22370987 / 21681408 : ℝ) * d 0 + (-85 / 5376 : ℝ)
      have ht0 : 0 ≤ t := by dsimp [t]; linarith
      have ht1 : t ≤ 1 := by dsimp [t]; linarith
      refine ⟨(1-t) • core0 2 + t • core0 0, ?_,
        (1-t) • core0 1 + t • core0 1, ?_, ?_⟩
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (by linarith) ht0 (by ring)
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (by linarith) ht0 (by ring)
      · ext axis
        fin_cases axis
        · change d 0 = ((1-t)*(21338603 / 67112961 : ℝ) + t*(-43705621 / 67112961 : ℝ)) -
            ((1-t)*(22367018 / 67112961 : ℝ) + t*(22367018 / 67112961 : ℝ))
          dsimp [t]
          linarith
        · change d 1 = ((1-t)*(22367018 / 67112961 : ℝ) + t*(21338603 / 67112961 : ℝ)) -
            ((1-t)*(-43705621 / 67112961 : ℝ) + t*(-43705621 / 67112961 : ℝ))
          dsimp [t]
          linarith

#print axioms certificate00

def normals02 : Fin 6 → Fin 2 → ℝ := ![![(-16375 : ℝ), (-759 : ℝ)], ![(-5376 : ℝ), (-5461 : ℝ)], ![(759 : ℝ), (-15616 : ℝ)], ![(5461 : ℝ), (85 : ℝ)], ![(15616 : ℝ), (16375 : ℝ)], ![(-85 : ℝ), (5376 : ℝ)]]
def thresholds02 : Fin 6 → ℝ := ![(5693194520148370555 / 364158349147011 : ℝ), (1926902298118681345 / 364158349147011 : ℝ), (5693194520148370555 / 364158349147011 : ℝ), (1926902298118681345 / 364158349147011 : ℝ), (5693194520148370555 / 364158349147011 : ℝ), (1926902298118681345 / 364158349147011 : ℝ)]

def certificate02 : RadialCertificate core0 core2 where
  normal := normals02
  threshold := thresholds02
  threshold_pos k := by
    fin_cases k <;> norm_num [thresholds02]
  positive_support d hd := by
    by_contra! h
    have h1 := h 1
    have h3 := h 3
    have h5 := h 5
    simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at h1 h3 h5
    change (-5376 : ℝ) * d 0 + (-5461 : ℝ) * d 1 ≤ 0 at h1
    change (5461 : ℝ) * d 0 + (85 : ℝ) * d 1 ≤ 0 at h3
    change (-85 : ℝ) * d 0 + (5376 : ℝ) * d 1 ≤ 0 at h5
    have hx : d 0 = 0 := by apply le_antisymm <;> linarith
    have hy : d 1 = 0 := by apply le_antisymm <;> linarith
    apply hd
    ext i
    fin_cases i
    · exact hx
    · exact hy
  boundary_decomposition k d heq hall := by
    fin_cases k
    · have hp := hall 5
      have hn := hall 1
      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn
      change (-16375 : ℝ) * d 0 + (-759 : ℝ) * d 1 = (5693194520148370555 / 364158349147011 : ℝ) at heq
      change (-85 : ℝ) * d 0 + (5376 : ℝ) * d 1 ≤ (1926902298118681345 / 364158349147011 : ℝ) at hp
      change (-5376 : ℝ) * d 0 + (-5461 : ℝ) * d 1 ≤ (1926902298118681345 / 364158349147011 : ℝ) at hn
      let t : ℝ := (-5426051 / 5420125 : ℝ) * d 1 + (70534239856096 / 72752127548025 : ℝ)
      have ht0 : 0 ≤ t := by dsimp [t]; linarith
      have ht1 : t ≤ 1 := by dsimp [t]; linarith
      refine ⟨(1-t) • core0 0 + t • core0 0, ?_,
        (1-t) • core2 1 + t • core2 2, ?_, ?_⟩
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (by linarith) ht0 (by ring)
      · exact (convex_convexHull ℝ (Set.range core2))
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (by linarith) ht0 (by ring)
      · ext axis
        fin_cases axis
        · change d 0 = ((1-t)*(-43705621 / 67112961 : ℝ) + t*(-43705621 / 67112961 : ℝ)) -
            ((1-t)*(5671354 / 16278153 : ℝ) + t*(4917667 / 16278153 : ℝ))
          dsimp [t]
          linarith
        · change d 1 = ((1-t)*(21338603 / 67112961 : ℝ) + t*(21338603 / 67112961 : ℝ)) -
            ((1-t)*(-10589021 / 16278153 : ℝ) + t*(5671354 / 16278153 : ℝ))
          dsimp [t]
          linarith
    · have hp := hall 0
      have hn := hall 2
      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn
      change (-5376 : ℝ) * d 0 + (-5461 : ℝ) * d 1 = (1926902298118681345 / 364158349147011 : ℝ) at heq
      change (-16375 : ℝ) * d 0 + (-759 : ℝ) * d 1 ≤ (5693194520148370555 / 364158349147011 : ℝ) at hp
      change (759 : ℝ) * d 0 + (-15616 : ℝ) * d 1 ≤ (5693194520148370555 / 364158349147011 : ℝ) at hn
      let t : ℝ := (22370987 / 22024213 : ℝ) * d 0 + (347161993060000 / 358513508918589 : ℝ)
      have ht0 : 0 ≤ t := by dsimp [t]; linarith
      have ht1 : t ≤ 1 := by dsimp [t]; linarith
      refine ⟨(1-t) • core0 0 + t • core0 1, ?_,
        (1-t) • core2 2 + t • core2 2, ?_, ?_⟩
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (by linarith) ht0 (by ring)
      · exact (convex_convexHull ℝ (Set.range core2))
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (by linarith) ht0 (by ring)
      · ext axis
        fin_cases axis
        · change d 0 = ((1-t)*(-43705621 / 67112961 : ℝ) + t*(22367018 / 67112961 : ℝ)) -
            ((1-t)*(4917667 / 16278153 : ℝ) + t*(4917667 / 16278153 : ℝ))
          dsimp [t]
          linarith
        · change d 1 = ((1-t)*(21338603 / 67112961 : ℝ) + t*(-43705621 / 67112961 : ℝ)) -
            ((1-t)*(5671354 / 16278153 : ℝ) + t*(5671354 / 16278153 : ℝ))
          dsimp [t]
          linarith
    · have hp := hall 1
      have hn := hall 3
      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn
      change (759 : ℝ) * d 0 + (-15616 : ℝ) * d 1 = (5693194520148370555 / 364158349147011 : ℝ) at heq
      change (-5376 : ℝ) * d 0 + (-5461 : ℝ) * d 1 ≤ (1926902298118681345 / 364158349147011 : ℝ) at hp
      change (5461 : ℝ) * d 0 + (85 : ℝ) * d 1 ≤ (1926902298118681345 / 364158349147011 : ℝ) at hn
      let t : ℝ := (5426051 / 5168896 : ℝ) * d 0 + (-11351515858589 / 346899915661056 : ℝ)
      have ht0 : 0 ≤ t := by dsimp [t]; linarith
      have ht1 : t ≤ 1 := by dsimp [t]; linarith
      refine ⟨(1-t) • core0 1 + t • core0 1, ?_,
        (1-t) • core2 2 + t • core2 0, ?_, ?_⟩
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (by linarith) ht0 (by ring)
      · exact (convex_convexHull ℝ (Set.range core2))
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (by linarith) ht0 (by ring)
      · ext axis
        fin_cases axis
        · change d 0 = ((1-t)*(22367018 / 67112961 : ℝ) + t*(22367018 / 67112961 : ℝ)) -
            ((1-t)*(4917667 / 16278153 : ℝ) + t*(-10589021 / 16278153 : ℝ))
          dsimp [t]
          linarith
        · change d 1 = ((1-t)*(-43705621 / 67112961 : ℝ) + t*(-43705621 / 67112961 : ℝ)) -
            ((1-t)*(5671354 / 16278153 : ℝ) + t*(4917667 / 16278153 : ℝ))
          dsimp [t]
          linarith
    · have hp := hall 2
      have hn := hall 4
      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn
      change (5461 : ℝ) * d 0 + (85 : ℝ) * d 1 = (1926902298118681345 / 364158349147011 : ℝ) at heq
      change (759 : ℝ) * d 0 + (-15616 : ℝ) * d 1 ≤ (5693194520148370555 / 364158349147011 : ℝ) at hp
      change (15616 : ℝ) * d 0 + (16375 : ℝ) * d 1 ≤ (5693194520148370555 / 364158349147011 : ℝ) at hn
      let t : ℝ := (22370987 / 22024213 : ℝ) * d 1 + (347161993060000 / 358513508918589 : ℝ)
      have ht0 : 0 ≤ t := by dsimp [t]; linarith
      have ht1 : t ≤ 1 := by dsimp [t]; linarith
      refine ⟨(1-t) • core0 1 + t • core0 2, ?_,
        (1-t) • core2 0 + t • core2 0, ?_, ?_⟩
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (by linarith) ht0 (by ring)
      · exact (convex_convexHull ℝ (Set.range core2))
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (by linarith) ht0 (by ring)
      · ext axis
        fin_cases axis
        · change d 0 = ((1-t)*(22367018 / 67112961 : ℝ) + t*(21338603 / 67112961 : ℝ)) -
            ((1-t)*(-10589021 / 16278153 : ℝ) + t*(-10589021 / 16278153 : ℝ))
          dsimp [t]
          linarith
        · change d 1 = ((1-t)*(-43705621 / 67112961 : ℝ) + t*(22367018 / 67112961 : ℝ)) -
            ((1-t)*(4917667 / 16278153 : ℝ) + t*(4917667 / 16278153 : ℝ))
          dsimp [t]
          linarith
    · have hp := hall 3
      have hn := hall 5
      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn
      change (15616 : ℝ) * d 0 + (16375 : ℝ) * d 1 = (5693194520148370555 / 364158349147011 : ℝ) at heq
      change (5461 : ℝ) * d 0 + (85 : ℝ) * d 1 ≤ (1926902298118681345 / 364158349147011 : ℝ) at hp
      change (-85 : ℝ) * d 0 + (5376 : ℝ) * d 1 ≤ (1926902298118681345 / 364158349147011 : ℝ) at hn
      let t : ℝ := (-5426051 / 5420125 : ℝ) * d 0 + (70534239856096 / 72752127548025 : ℝ)
      have ht0 : 0 ≤ t := by dsimp [t]; linarith
      have ht1 : t ≤ 1 := by dsimp [t]; linarith
      refine ⟨(1-t) • core0 2 + t • core0 2, ?_,
        (1-t) • core2 0 + t • core2 1, ?_, ?_⟩
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (by linarith) ht0 (by ring)
      · exact (convex_convexHull ℝ (Set.range core2))
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (by linarith) ht0 (by ring)
      · ext axis
        fin_cases axis
        · change d 0 = ((1-t)*(21338603 / 67112961 : ℝ) + t*(21338603 / 67112961 : ℝ)) -
            ((1-t)*(-10589021 / 16278153 : ℝ) + t*(5671354 / 16278153 : ℝ))
          dsimp [t]
          linarith
        · change d 1 = ((1-t)*(22367018 / 67112961 : ℝ) + t*(22367018 / 67112961 : ℝ)) -
            ((1-t)*(4917667 / 16278153 : ℝ) + t*(-10589021 / 16278153 : ℝ))
          dsimp [t]
          linarith
    · have hp := hall 4
      have hn := hall 0
      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn
      change (-85 : ℝ) * d 0 + (5376 : ℝ) * d 1 = (1926902298118681345 / 364158349147011 : ℝ) at heq
      change (15616 : ℝ) * d 0 + (16375 : ℝ) * d 1 ≤ (5693194520148370555 / 364158349147011 : ℝ) at hp
      change (-16375 : ℝ) * d 0 + (-759 : ℝ) * d 1 ≤ (5693194520148370555 / 364158349147011 : ℝ) at hn
      let t : ℝ := (-22370987 / 21681408 : ℝ) * d 0 + (-1584205494235 / 50419039525632 : ℝ)
      have ht0 : 0 ≤ t := by dsimp [t]; linarith
      have ht1 : t ≤ 1 := by dsimp [t]; linarith
      refine ⟨(1-t) • core0 2 + t • core0 0, ?_,
        (1-t) • core2 1 + t • core2 1, ?_, ?_⟩
      · exact (convex_convexHull ℝ (Set.range core0))
          (subset_convexHull ℝ _ ⟨2, rfl⟩)
          (subset_convexHull ℝ _ ⟨0, rfl⟩)
          (by linarith) ht0 (by ring)
      · exact (convex_convexHull ℝ (Set.range core2))
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (subset_convexHull ℝ _ ⟨1, rfl⟩)
          (by linarith) ht0 (by ring)
      · ext axis
        fin_cases axis
        · change d 0 = ((1-t)*(21338603 / 67112961 : ℝ) + t*(-43705621 / 67112961 : ℝ)) -
            ((1-t)*(5671354 / 16278153 : ℝ) + t*(5671354 / 16278153 : ℝ))
          dsimp [t]
          linarith
        · change d 1 = ((1-t)*(22367018 / 67112961 : ℝ) + t*(21338603 / 67112961 : ℝ)) -
            ((1-t)*(-10589021 / 16278153 : ℝ) + t*(-10589021 / 16278153 : ℝ))
          dsimp [t]
          linarith

#print axioms certificate02

theorem feature0_iff (p q r : Fin 2 → ℝ) (k : Fin 6) :
    Holds (join3 p q r) (features0 k) ↔
      thresholds00 k ≤ linear (normals00 k) (q - p) := by
  fin_cases k
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (118431307513 / 122167960007 : ℝ) ≤ (1 : ℝ) * p 0 + ((85 / 5461 : ℝ) * p 1 + ((-1 : ℝ) * q 0 + ((-85 / 5461 : ℝ) * q 1 + ((0 : ℝ) * r 0 + ((0 : ℝ) * r 1))))) ↔
      (118431307513 / 22370987 : ℝ) ≤ (-5461 : ℝ) * (q 0 - p 0) +
        (-85 : ℝ) * (q 1 - p 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (118431307513 / 122167960007 : ℝ) ≤ (5376 / 5461 : ℝ) * p 0 + ((1 : ℝ) * p 1 + ((-5376 / 5461 : ℝ) * q 0 + ((-1 : ℝ) * q 1 + ((0 : ℝ) * r 0 + ((0 : ℝ) * r 1))))) ↔
      (118431307513 / 22370987 : ℝ) ≤ (-5376 : ℝ) * (q 0 - p 0) +
        (-5461 : ℝ) * (q 1 - p 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (118431307513 / 120266426112 : ℝ) ≤ (-85 / 5376 : ℝ) * p 0 + ((1 : ℝ) * p 1 + ((85 / 5376 : ℝ) * q 0 + ((-1 : ℝ) * q 1 + ((0 : ℝ) * r 0 + ((0 : ℝ) * r 1))))) ↔
      (118431307513 / 22370987 : ℝ) ≤ (85 : ℝ) * (q 0 - p 0) +
        (-5376 : ℝ) * (q 1 - p 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (118431307513 / 122167960007 : ℝ) ≤ (-1 : ℝ) * p 0 + ((-85 / 5461 : ℝ) * p 1 + ((1 : ℝ) * q 0 + ((85 / 5461 : ℝ) * q 1 + ((0 : ℝ) * r 0 + ((0 : ℝ) * r 1))))) ↔
      (118431307513 / 22370987 : ℝ) ≤ (5461 : ℝ) * (q 0 - p 0) +
        (85 : ℝ) * (q 1 - p 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (118431307513 / 122167960007 : ℝ) ≤ (-5376 / 5461 : ℝ) * p 0 + ((-1 : ℝ) * p 1 + ((5376 / 5461 : ℝ) * q 0 + ((1 : ℝ) * q 1 + ((0 : ℝ) * r 0 + ((0 : ℝ) * r 1))))) ↔
      (118431307513 / 22370987 : ℝ) ≤ (5376 : ℝ) * (q 0 - p 0) +
        (5461 : ℝ) * (q 1 - p 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (118431307513 / 120266426112 : ℝ) ≤ (85 / 5376 : ℝ) * p 0 + ((-1 : ℝ) * p 1 + ((-85 / 5376 : ℝ) * q 0 + ((1 : ℝ) * q 1 + ((0 : ℝ) * r 0 + ((0 : ℝ) * r 1))))) ↔
      (118431307513 / 22370987 : ℝ) ≤ (-85 : ℝ) * (q 0 - p 0) +
        (5376 : ℝ) * (q 1 - p 1)
    constructor <;> intro h <;> linarith only [h]

theorem feature1_iff (p q r : Fin 2 → ℝ) (k : Fin 6) :
    Holds (join3 p q r) (features1 k) ↔
      thresholds02 k ≤ linear (normals02 k) (r - p) := by
  fin_cases k
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (1138638904029674111 / 1192618593456461025 : ℝ) ≤ (1 : ℝ) * p 0 + ((759 / 16375 : ℝ) * p 1 + ((0 : ℝ) * q 0 + ((0 : ℝ) * q 1 + ((-1 : ℝ) * r 0 + ((-759 / 16375 : ℝ) * r 1))))) ↔
      (5693194520148370555 / 364158349147011 : ℝ) ≤ (-16375 : ℝ) * (r 0 - p 0) +
        (-759 : ℝ) * (r 1 - p 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (1926902298118681345 / 1988668744691827071 : ℝ) ≤ (5376 / 5461 : ℝ) * p 0 + ((1 : ℝ) * p 1 + ((0 : ℝ) * q 0 + ((0 : ℝ) * q 1 + ((-5376 / 5461 : ℝ) * r 0 + ((-1 : ℝ) * r 1))))) ↔
      (1926902298118681345 / 364158349147011 : ℝ) ≤ (-5376 : ℝ) * (r 0 - p 0) +
        (-5461 : ℝ) * (r 1 - p 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (5693194520148370555 / 5686696780279723776 : ℝ) ≤ (-759 / 15616 : ℝ) * p 0 + ((1 : ℝ) * p 1 + ((0 : ℝ) * q 0 + ((0 : ℝ) * q 1 + ((759 / 15616 : ℝ) * r 0 + ((-1 : ℝ) * r 1))))) ↔
      (5693194520148370555 / 364158349147011 : ℝ) ≤ (759 : ℝ) * (r 0 - p 0) +
        (-15616 : ℝ) * (r 1 - p 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (1926902298118681345 / 1988668744691827071 : ℝ) ≤ (-1 : ℝ) * p 0 + ((-85 / 5461 : ℝ) * p 1 + ((0 : ℝ) * q 0 + ((0 : ℝ) * q 1 + ((1 : ℝ) * r 0 + ((85 / 5461 : ℝ) * r 1))))) ↔
      (1926902298118681345 / 364158349147011 : ℝ) ≤ (5461 : ℝ) * (r 0 - p 0) +
        (85 : ℝ) * (r 1 - p 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (1138638904029674111 / 1192618593456461025 : ℝ) ≤ (-15616 / 16375 : ℝ) * p 0 + ((-1 : ℝ) * p 1 + ((0 : ℝ) * q 0 + ((0 : ℝ) * q 1 + ((15616 / 16375 : ℝ) * r 0 + ((1 : ℝ) * r 1))))) ↔
      (5693194520148370555 / 364158349147011 : ℝ) ≤ (15616 : ℝ) * (r 0 - p 0) +
        (16375 : ℝ) * (r 1 - p 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (275271756874097335 / 279673612144904448 : ℝ) ≤ (85 / 5376 : ℝ) * p 0 + ((-1 : ℝ) * p 1 + ((0 : ℝ) * q 0 + ((0 : ℝ) * q 1 + ((-85 / 5376 : ℝ) * r 0 + ((1 : ℝ) * r 1))))) ↔
      (1926902298118681345 / 364158349147011 : ℝ) ≤ (-85 : ℝ) * (r 0 - p 0) +
        (5376 : ℝ) * (r 1 - p 1)
    constructor <;> intro h <;> linarith only [h]

theorem feature2_iff (p q r : Fin 2 → ℝ) (k : Fin 6) :
    Holds (join3 p q r) (features2 k) ↔
      thresholds02 k ≤ linear (normals02 k) (r - q) := by
  fin_cases k
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (1138638904029674111 / 1192618593456461025 : ℝ) ≤ (0 : ℝ) * p 0 + ((0 : ℝ) * p 1 + ((1 : ℝ) * q 0 + ((759 / 16375 : ℝ) * q 1 + ((-1 : ℝ) * r 0 + ((-759 / 16375 : ℝ) * r 1))))) ↔
      (5693194520148370555 / 364158349147011 : ℝ) ≤ (-16375 : ℝ) * (r 0 - q 0) +
        (-759 : ℝ) * (r 1 - q 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (1926902298118681345 / 1988668744691827071 : ℝ) ≤ (0 : ℝ) * p 0 + ((0 : ℝ) * p 1 + ((5376 / 5461 : ℝ) * q 0 + ((1 : ℝ) * q 1 + ((-5376 / 5461 : ℝ) * r 0 + ((-1 : ℝ) * r 1))))) ↔
      (1926902298118681345 / 364158349147011 : ℝ) ≤ (-5376 : ℝ) * (r 0 - q 0) +
        (-5461 : ℝ) * (r 1 - q 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (5693194520148370555 / 5686696780279723776 : ℝ) ≤ (0 : ℝ) * p 0 + ((0 : ℝ) * p 1 + ((-759 / 15616 : ℝ) * q 0 + ((1 : ℝ) * q 1 + ((759 / 15616 : ℝ) * r 0 + ((-1 : ℝ) * r 1))))) ↔
      (5693194520148370555 / 364158349147011 : ℝ) ≤ (759 : ℝ) * (r 0 - q 0) +
        (-15616 : ℝ) * (r 1 - q 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (1926902298118681345 / 1988668744691827071 : ℝ) ≤ (0 : ℝ) * p 0 + ((0 : ℝ) * p 1 + ((-1 : ℝ) * q 0 + ((-85 / 5461 : ℝ) * q 1 + ((1 : ℝ) * r 0 + ((85 / 5461 : ℝ) * r 1))))) ↔
      (1926902298118681345 / 364158349147011 : ℝ) ≤ (5461 : ℝ) * (r 0 - q 0) +
        (85 : ℝ) * (r 1 - q 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (1138638904029674111 / 1192618593456461025 : ℝ) ≤ (0 : ℝ) * p 0 + ((0 : ℝ) * p 1 + ((-15616 / 16375 : ℝ) * q 0 + ((-1 : ℝ) * q 1 + ((15616 / 16375 : ℝ) * r 0 + ((1 : ℝ) * r 1))))) ↔
      (5693194520148370555 / 364158349147011 : ℝ) ≤ (15616 : ℝ) * (r 0 - q 0) +
        (16375 : ℝ) * (r 1 - q 1)
    constructor <;> intro h <;> linarith only [h]
  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
    change (275271756874097335 / 279673612144904448 : ℝ) ≤ (0 : ℝ) * p 0 + ((0 : ℝ) * p 1 + ((85 / 5376 : ℝ) * q 0 + ((-1 : ℝ) * q 1 + ((-85 / 5376 : ℝ) * r 0 + ((1 : ℝ) * r 1))))) ↔
      (1926902298118681345 / 364158349147011 : ℝ) ≤ (-85 : ℝ) * (r 0 - q 0) +
        (5376 : ℝ) * (r 1 - q 1)
    constructor <;> intro h <;> linarith only [h]

end
end SixTrianglePilot.CoreSeparation
