-- Generated by extract.py from the frozen certificate. Do not hand-edit.
-- Certificate SHA-256: f8b2306312064ae083d91a97bd01d1669970685d1e3c0b71b3628f2ecfc773be
-- Complete joint terminal at outer path: 0000000001
-- Only the extracted linear system is formalized; see README.md.
import Pilot.Farkas
import Mathlib.Data.Fin.VecNotation
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.FinCases

set_option maxRecDepth 4096
set_option maxHeartbeats 2000000

namespace SixTrianglePilot.Selected
noncomputable section
open scoped BigOperators

structure Constraint where
  a : Fin 6 → ℝ
  b : ℝ

def Holds (x : Fin 6 → ℝ) (row : Constraint) : Prop := row.b ≤ linear row.a x

def lower : Fin 6 → ℝ := ![(5590325 / 8388608 : ℝ), (5592405 / 8388608 : ℝ), (5590325 / 8388608 : ℝ), (5590325 / 8388608 : ℝ), (11167915 / 16777216 : ℝ), (11167915 / 16777216 : ℝ)]
def upper : Fin 6 → ℝ := ![(11311571 / 16777216 : ℝ), (3447193 / 2097152 : ℝ), (1445953 / 2097152 : ℝ), (3447193 / 2097152 : ℝ), (27315465 / 16777216 : ℝ), (27315465 / 16777216 : ℝ)]
def InBox (x : Fin 6 → ℝ) : Prop := (∀ j, lower j ≤ x j) ∧ (∀ j, x j ≤ upper j)

def base_0 : Constraint := ⟨![(1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (5590325 / 8388608 : ℝ)⟩
def base_1 : Constraint := ⟨![(-1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (-11311571 / 16777216 : ℝ)⟩
def base_2 : Constraint := ⟨![(0 : ℝ), (1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (5592405 / 8388608 : ℝ)⟩
def base_3 : Constraint := ⟨![(0 : ℝ), (-1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (-3447193 / 2097152 : ℝ)⟩
def base_4 : Constraint := ⟨![(1 : ℝ), (1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (5592405 / 4194304 : ℝ)⟩
def base_5 : Constraint := ⟨![(0 : ℝ), (1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (5592405 / 8388608 : ℝ)⟩
def base_6 : Constraint := ⟨![(-66902 / 66903 : ℝ), (1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (2779477 / 280611520512 : ℝ)⟩
def base_7 : Constraint := ⟨![(-1 : ℝ), (3521 / 945430 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (-2649522672267 / 3965420830720 : ℝ)⟩
def base_8 : Constraint := ⟨![(-1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (-11311571 / 16777216 : ℝ)⟩
def base_9 : Constraint := ⟨![(-1 : ℝ), (-126760 / 253519 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (-6331291577349 / 4253343023104 : ℝ)⟩
def base_10 : Constraint := ⟨![(0 : ℝ), (-1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (-3447193 / 2097152 : ℝ)⟩
def base_11 : Constraint := ⟨![(1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (5590325 / 8388608 : ℝ)⟩
def base_12 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (5590325 / 8388608 : ℝ)⟩
def base_13 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (-1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (-1445953 / 2097152 : ℝ)⟩
def base_14 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (1 : ℝ), (0 : ℝ), (0 : ℝ)], (5590325 / 8388608 : ℝ)⟩
def base_15 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (-1 : ℝ), (0 : ℝ), (0 : ℝ)], (-3447193 / 2097152 : ℝ)⟩
def base_16 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (1 : ℝ), (1 : ℝ), (0 : ℝ), (0 : ℝ)], (5592405 / 4194304 : ℝ)⟩
def base_17 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (1 : ℝ), (0 : ℝ), (0 : ℝ)], (5590325 / 8388608 : ℝ)⟩
def base_18 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (-1 : ℝ), (1956 / 125299 : ℝ), (0 : ℝ), (0 : ℝ)], (-1396482876159 / 2102168387584 : ℝ)⟩
def base_19 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (-1 : ℝ), (243971 / 15767644 : ℝ), (0 : ℝ), (0 : ℝ)], (-43939609069431 / 66134292299776 : ℝ)⟩
def base_20 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (-1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (-1445953 / 2097152 : ℝ)⟩
def base_21 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (-378651 / 378653 : ℝ), (-1 : ℝ), (0 : ℝ), (0 : ℝ)], (-14679034826353 / 6352743170048 : ℝ)⟩
def base_22 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (-1 : ℝ), (0 : ℝ), (0 : ℝ)], (-3447193 / 2097152 : ℝ)⟩
def base_23 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (1 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)], (5590325 / 8388608 : ℝ)⟩
def base_24 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (1 : ℝ), (0 : ℝ)], (11167915 / 16777216 : ℝ)⟩
def base_25 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (-1 : ℝ), (0 : ℝ)], (-27315465 / 16777216 : ℝ)⟩
def base_26 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (1 : ℝ)], (11167915 / 16777216 : ℝ)⟩
def base_27 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (-1 : ℝ)], (-27315465 / 16777216 : ℝ)⟩
def base_28 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (1 : ℝ), (2656682 / 5350287 : ℝ)], (132063182702837 / 89762920660992 : ℝ)⟩
def base_29 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (1 : ℝ)], (11167915 / 16777216 : ℝ)⟩
def base_30 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (-1 : ℝ), (0 : ℝ)], (-27315465 / 16777216 : ℝ)⟩
def base_31 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (-1 : ℝ), (-1 : ℝ)], (-38779251 / 16777216 : ℝ)⟩
def base_32 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (-1 : ℝ)], (-27315465 / 16777216 : ℝ)⟩
def base_33 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (1 : ℝ), (0 : ℝ)], (11167915 / 16777216 : ℝ)⟩
def baseRows : Fin 34 → Constraint := ![base_0, base_1, base_2, base_3, base_4, base_5, base_6, base_7, base_8, base_9, base_10, base_11, base_12, base_13, base_14, base_15, base_16, base_17, base_18, base_19, base_20, base_21, base_22, base_23, base_24, base_25, base_26, base_27, base_28, base_29, base_30, base_31, base_32, base_33]

def feature_0_1 : Constraint := ⟨![(5376 / 5461 : ℝ), (1 : ℝ), (-5376 / 5461 : ℝ), (-1 : ℝ), (0 : ℝ), (0 : ℝ)], (118431307513 / 122167960007 : ℝ)⟩
def feature_0_4 : Constraint := ⟨![(-5376 / 5461 : ℝ), (-1 : ℝ), (5376 / 5461 : ℝ), (1 : ℝ), (0 : ℝ), (0 : ℝ)], (118431307513 / 122167960007 : ℝ)⟩
def feature_1_2 : Constraint := ⟨![(-759 / 15616 : ℝ), (1 : ℝ), (0 : ℝ), (0 : ℝ), (759 / 15616 : ℝ), (-1 : ℝ)], (5693194520148370555 / 5686696780279723776 : ℝ)⟩
def feature_1_4 : Constraint := ⟨![(-15616 / 16375 : ℝ), (-1 : ℝ), (0 : ℝ), (0 : ℝ), (15616 / 16375 : ℝ), (1 : ℝ)], (1138638904029674111 / 1192618593456461025 : ℝ)⟩
def feature_2_2 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (-759 / 15616 : ℝ), (1 : ℝ), (759 / 15616 : ℝ), (-1 : ℝ)], (5693194520148370555 / 5686696780279723776 : ℝ)⟩
def feature_2_4 : Constraint := ⟨![(0 : ℝ), (0 : ℝ), (-15616 / 16375 : ℝ), (-1 : ℝ), (15616 / 16375 : ℝ), (1 : ℝ)], (1138638904029674111 / 1192618593456461025 : ℝ)⟩

def leafRows_0 : Fin 7 → Constraint := ![base_3, base_9, base_12, base_25, base_26, feature_0_1, feature_2_2]
def weights_0 : Fin 7 → ℝ := ![(764205 / 8388608 : ℝ), (740783 / 4194304 : ℝ), (3109429 / 16777216 : ℝ), (146297 / 16777216 : ℝ), (1504991 / 8388608 : ℝ), (1504991 / 8388608 : ℝ), (1504991 / 8388608 : ℝ)]
def residual_0 : Fin 6 → ℝ := ![(-155 / 22905094144 : ℝ), (9887 / 1063335755776 : ℝ), (-1674013 / 715371900305408 : ℝ), (0 : ℝ), (1193 / 130996502528 : ℝ), (0 : ℝ)]
def beta_0 : ℝ := (1468380614005870621606858226538722841259 / 8656505077831275031392551785277983555584 : ℝ)

theorem leaf_0_infeasible (x : Fin 6 → ℝ) (hbox : InBox x)
    (hbase : ∀ i : Fin 34, Holds x (baseRows i))
    (h0_1 : Holds x feature_0_1)
    (h2_2 : Holds x feature_2_2)
    : False := by
  have hw : ∀ i, 0 ≤ weights_0 i := by
    intro i; fin_cases i <;> norm_num [weights_0]
  have hr : ∀ j, (∑ i, weights_0 i * (leafRows_0 i).a j) = residual_0 j := by
    intro j; fin_cases j <;> norm_num [weights_0, leafRows_0, residual_0, base_3, base_9, base_12, base_25, base_26, feature_0_1, feature_2_2, Fin.sum_univ_succ]
  have hb : (∑ i, weights_0 i * (leafRows_0 i).b) = beta_0 := by
    norm_num [weights_0, leafRows_0, beta_0, base_3, base_9, base_12, base_25, base_26, feature_0_1, feature_2_2, Fin.sum_univ_succ]
  have hgap : boxSupport residual_0 lower upper < beta_0 := by
    norm_num [boxSupport, residual_0, lower, upper, beta_0, Fin.sum_univ_succ]
  have hrows : ∀ i, (leafRows_0 i).b ≤ linear (leafRows_0 i).a x := by
    intro i; fin_cases i
    · exact hbase (3 : Fin 34)
    · exact hbase (9 : Fin 34)
    · exact hbase (12 : Fin 34)
    · exact hbase (25 : Fin 34)
    · exact hbase (26 : Fin 34)
    · exact h0_1
    · exact h2_2
  exact residualAwareFarkas (fun i => (leafRows_0 i).a) (fun i => (leafRows_0 i).b)
    weights_0 residual_0 beta_0 lower upper x hw hr hb hgap hbox.1 hbox.2 hrows

def leafRows_1 : Fin 7 → Constraint := ![base_0, base_3, base_14, base_16, base_31, feature_2_4, feature_1_2]
def weights_1 : Fin 7 → ℝ := ![(1479 / 2097152 : ℝ), (121719 / 8388608 : ℝ), (127635 / 8388608 : ℝ), (5252045 / 16777216 : ℝ), (5263877 / 16777216 : ℝ), (5507315 / 16777216 : ℝ), (121719 / 8388608 : ℝ)]
def residual_1 : Fin 6 → ℝ := ![(-465 / 130996502528 : ℝ), (0 : ℝ), (1167 / 54945382400 : ℝ), (0 : ℝ), (-7589061 / 429013545779200 : ℝ), (0 : ℝ)]
def beta_1 : ℝ := (28143133172618921152879848818873 / 4095445947977802735140103027425280 : ℝ)

theorem leaf_1_infeasible (x : Fin 6 → ℝ) (hbox : InBox x)
    (hbase : ∀ i : Fin 34, Holds x (baseRows i))
    (_h0_1 : Holds x feature_0_1)
    (h2_4 : Holds x feature_2_4)
    (h1_2 : Holds x feature_1_2)
    : False := by
  have hw : ∀ i, 0 ≤ weights_1 i := by
    intro i; fin_cases i <;> norm_num [weights_1]
  have hr : ∀ j, (∑ i, weights_1 i * (leafRows_1 i).a j) = residual_1 j := by
    intro j; fin_cases j <;> norm_num [weights_1, leafRows_1, residual_1, base_0, base_3, base_14, base_16, base_31, feature_2_4, feature_1_2, Fin.sum_univ_succ]
  have hb : (∑ i, weights_1 i * (leafRows_1 i).b) = beta_1 := by
    norm_num [weights_1, leafRows_1, beta_1, base_0, base_3, base_14, base_16, base_31, feature_2_4, feature_1_2, Fin.sum_univ_succ]
  have hgap : boxSupport residual_1 lower upper < beta_1 := by
    norm_num [boxSupport, residual_1, lower, upper, beta_1, Fin.sum_univ_succ]
  have hrows : ∀ i, (leafRows_1 i).b ≤ linear (leafRows_1 i).a x := by
    intro i; fin_cases i
    · exact hbase (0 : Fin 34)
    · exact hbase (3 : Fin 34)
    · exact hbase (14 : Fin 34)
    · exact hbase (16 : Fin 34)
    · exact hbase (31 : Fin 34)
    · exact h2_4
    · exact h1_2
  exact residualAwareFarkas (fun i => (leafRows_1 i).a) (fun i => (leafRows_1 i).b)
    weights_1 residual_1 beta_1 lower upper x hw hr hb hgap hbox.1 hbox.2 hrows

def leafRows_2 : Fin 7 → Constraint := ![base_7, base_14, base_16, base_27, base_31, feature_0_1, feature_1_4]
def weights_2 : Fin 7 → ℝ := ![(127683 / 16777216 : ℝ), (64783 / 16777216 : ℝ), (2048681 / 8388608 : ℝ), (96471 / 8388608 : ℝ), (3969679 / 16777216 : ℝ), (4162145 / 16777216 : ℝ), (4162621 / 16777216 : ℝ)]
def residual_2 : Fin 6 → ℝ := ![(-16347721 / 1500283666432000 : ℝ), (-452837 / 15861683322880 : ℝ), (1181 / 45810188288 : ℝ), (0 : ℝ), (-4089 / 274726912000 : ℝ), (0 : ℝ)]
def beta_2 : ℝ := (40705645540360248643311465378477221746223 / 173317702485576456654129795345075614515200 : ℝ)

theorem leaf_2_infeasible (x : Fin 6 → ℝ) (hbox : InBox x)
    (hbase : ∀ i : Fin 34, Holds x (baseRows i))
    (h0_1 : Holds x feature_0_1)
    (_h2_4 : Holds x feature_2_4)
    (h1_4 : Holds x feature_1_4)
    : False := by
  have hw : ∀ i, 0 ≤ weights_2 i := by
    intro i; fin_cases i <;> norm_num [weights_2]
  have hr : ∀ j, (∑ i, weights_2 i * (leafRows_2 i).a j) = residual_2 j := by
    intro j; fin_cases j <;> norm_num [weights_2, leafRows_2, residual_2, base_7, base_14, base_16, base_27, base_31, feature_0_1, feature_1_4, Fin.sum_univ_succ]
  have hb : (∑ i, weights_2 i * (leafRows_2 i).b) = beta_2 := by
    norm_num [weights_2, leafRows_2, beta_2, base_7, base_14, base_16, base_27, base_31, feature_0_1, feature_1_4, Fin.sum_univ_succ]
  have hgap : boxSupport residual_2 lower upper < beta_2 := by
    norm_num [boxSupport, residual_2, lower, upper, beta_2, Fin.sum_univ_succ]
  have hrows : ∀ i, (leafRows_2 i).b ≤ linear (leafRows_2 i).a x := by
    intro i; fin_cases i
    · exact hbase (7 : Fin 34)
    · exact hbase (14 : Fin 34)
    · exact hbase (16 : Fin 34)
    · exact hbase (27 : Fin 34)
    · exact hbase (31 : Fin 34)
    · exact h0_1
    · exact h1_4
  exact residualAwareFarkas (fun i => (leafRows_2 i).a) (fun i => (leafRows_2 i).b)
    weights_2 residual_2 beta_2 lower upper x hw hr hb hgap hbox.1 hbox.2 hrows

def leafRows_3 : Fin 7 → Constraint := ![base_0, base_15, base_21, base_25, base_26, feature_0_4, feature_1_2]
def weights_3 : Fin 7 → ℝ := ![(3410613 / 16777216 : ℝ), (51371 / 16777216 : ℝ), (3250163 / 16777216 : ℝ), (40117 / 4194304 : ℝ), (1650767 / 8388608 : ℝ), (1650767 / 8388608 : ℝ), (1650767 / 8388608 : ℝ)]
def residual_3 : Fin 6 → ℝ := ![(-27690861 / 715371900305408 : ℝ), (0 : ℝ), (147614859 / 34692330451632128 : ℝ), (0 : ℝ), (-1991 / 130996502528 : ℝ), (0 : ℝ)]
def beta_3 : ℝ := (2404966862918867451789941242365371052167 / 12929254285619798849245555209474888695808 : ℝ)

theorem leaf_3_infeasible (x : Fin 6 → ℝ) (hbox : InBox x)
    (hbase : ∀ i : Fin 34, Holds x (baseRows i))
    (h0_4 : Holds x feature_0_4)
    (h1_2 : Holds x feature_1_2)
    : False := by
  have hw : ∀ i, 0 ≤ weights_3 i := by
    intro i; fin_cases i <;> norm_num [weights_3]
  have hr : ∀ j, (∑ i, weights_3 i * (leafRows_3 i).a j) = residual_3 j := by
    intro j; fin_cases j <;> norm_num [weights_3, leafRows_3, residual_3, base_0, base_15, base_21, base_25, base_26, feature_0_4, feature_1_2, Fin.sum_univ_succ]
  have hb : (∑ i, weights_3 i * (leafRows_3 i).b) = beta_3 := by
    norm_num [weights_3, leafRows_3, beta_3, base_0, base_15, base_21, base_25, base_26, feature_0_4, feature_1_2, Fin.sum_univ_succ]
  have hgap : boxSupport residual_3 lower upper < beta_3 := by
    norm_num [boxSupport, residual_3, lower, upper, beta_3, Fin.sum_univ_succ]
  have hrows : ∀ i, (leafRows_3 i).b ≤ linear (leafRows_3 i).a x := by
    intro i; fin_cases i
    · exact hbase (0 : Fin 34)
    · exact hbase (15 : Fin 34)
    · exact hbase (21 : Fin 34)
    · exact hbase (25 : Fin 34)
    · exact hbase (26 : Fin 34)
    · exact h0_4
    · exact h1_2
  exact residualAwareFarkas (fun i => (leafRows_3 i).a) (fun i => (leafRows_3 i).b)
    weights_3 residual_3 beta_3 lower upper x hw hr hb hgap hbox.1 hbox.2 hrows

def leafRows_4 : Fin 7 → Constraint := ![base_4, base_6, base_12, base_15, base_31, feature_1_4, feature_2_2]
def weights_4 : Fin 7 → ℝ := ![(5379679 / 16777216 : ℝ), (31909 / 4194304 : ℝ), (1479 / 2097152 : ℝ), (121719 / 8388608 : ℝ), (5263877 / 16777216 : ℝ), (5507315 / 16777216 : ℝ), (121719 / 8388608 : ℝ)]
def residual_4 : Fin 6 → ℝ := ![(57869051 / 3676010918707200 : ℝ), (0 : ℝ), (-465 / 130996502528 : ℝ), (0 : ℝ), (-7589061 / 429013545779200 : ℝ), (0 : ℝ)]
def beta_4 : ℝ := (627964207872591211302659878793129153 / 91332540085852978796359437614611169280 : ℝ)

theorem leaf_4_infeasible (x : Fin 6 → ℝ) (hbox : InBox x)
    (hbase : ∀ i : Fin 34, Holds x (baseRows i))
    (_h0_4 : Holds x feature_0_4)
    (h1_4 : Holds x feature_1_4)
    (h2_2 : Holds x feature_2_2)
    : False := by
  have hw : ∀ i, 0 ≤ weights_4 i := by
    intro i; fin_cases i <;> norm_num [weights_4]
  have hr : ∀ j, (∑ i, weights_4 i * (leafRows_4 i).a j) = residual_4 j := by
    intro j; fin_cases j <;> norm_num [weights_4, leafRows_4, residual_4, base_4, base_6, base_12, base_15, base_31, feature_1_4, feature_2_2, Fin.sum_univ_succ]
  have hb : (∑ i, weights_4 i * (leafRows_4 i).b) = beta_4 := by
    norm_num [weights_4, leafRows_4, beta_4, base_4, base_6, base_12, base_15, base_31, feature_1_4, feature_2_2, Fin.sum_univ_succ]
  have hgap : boxSupport residual_4 lower upper < beta_4 := by
    norm_num [boxSupport, residual_4, lower, upper, beta_4, Fin.sum_univ_succ]
  have hrows : ∀ i, (leafRows_4 i).b ≤ linear (leafRows_4 i).a x := by
    intro i; fin_cases i
    · exact hbase (4 : Fin 34)
    · exact hbase (6 : Fin 34)
    · exact hbase (12 : Fin 34)
    · exact hbase (15 : Fin 34)
    · exact hbase (31 : Fin 34)
    · exact h1_4
    · exact h2_2
  exact residualAwareFarkas (fun i => (leafRows_4 i).a) (fun i => (leafRows_4 i).b)
    weights_4 residual_4 beta_4 lower upper x hw hr hb hgap hbox.1 hbox.2 hrows

def leafRows_5 : Fin 7 → Constraint := ![base_4, base_6, base_19, base_27, base_31, feature_0_4, feature_2_4]
def weights_5 : Fin 7 → ℝ := ![(4129373 / 16777216 : ℝ), (32389 / 16777216 : ℝ), (63131 / 8388608 : ℝ), (192993 / 16777216 : ℝ), (1985361 / 8388608 : ℝ), (2080881 / 8388608 : ℝ), (4163715 / 16777216 : ℝ)]
def residual_5 : Fin 6 → ℝ := ![(-16339535 / 6129678054064128 : ℝ), (0 : ℝ), (4352291 / 150028366643200 : ℝ), (5028835 / 132268584599552 : ℝ), (69 / 27472691200 : ℝ), (0 : ℝ)]
def beta_5 : ℝ := (7568129490887230978358828631890379424197654793 / 32231067693287445590036767933135824219097006080 : ℝ)

theorem leaf_5_infeasible (x : Fin 6 → ℝ) (hbox : InBox x)
    (hbase : ∀ i : Fin 34, Holds x (baseRows i))
    (h0_4 : Holds x feature_0_4)
    (_h1_4 : Holds x feature_1_4)
    (h2_4 : Holds x feature_2_4)
    : False := by
  have hw : ∀ i, 0 ≤ weights_5 i := by
    intro i; fin_cases i <;> norm_num [weights_5]
  have hr : ∀ j, (∑ i, weights_5 i * (leafRows_5 i).a j) = residual_5 j := by
    intro j; fin_cases j <;> norm_num [weights_5, leafRows_5, residual_5, base_4, base_6, base_19, base_27, base_31, feature_0_4, feature_2_4, Fin.sum_univ_succ]
  have hb : (∑ i, weights_5 i * (leafRows_5 i).b) = beta_5 := by
    norm_num [weights_5, leafRows_5, beta_5, base_4, base_6, base_19, base_27, base_31, feature_0_4, feature_2_4, Fin.sum_univ_succ]
  have hgap : boxSupport residual_5 lower upper < beta_5 := by
    norm_num [boxSupport, residual_5, lower, upper, beta_5, Fin.sum_univ_succ]
  have hrows : ∀ i, (leafRows_5 i).b ≤ linear (leafRows_5 i).a x := by
    intro i; fin_cases i
    · exact hbase (4 : Fin 34)
    · exact hbase (6 : Fin 34)
    · exact hbase (19 : Fin 34)
    · exact hbase (27 : Fin 34)
    · exact hbase (31 : Fin 34)
    · exact h0_4
    · exact h2_4
  exact residualAwareFarkas (fun i => (leafRows_5 i).a) (fun i => (leafRows_5 i).b)
    weights_5 residual_5 beta_5 lower upper x hw hr hb hgap hbox.1 hbox.2 hrows

/-- Every retained alternative of the selected terminal is covered.
The hypotheses are explicit linear constraints, not triangle-packability. -/
theorem selectedTerminalInfeasible (x : Fin 6 → ℝ) (hbox : InBox x)
    (hbase : ∀ i : Fin 34, Holds x (baseRows i))
    (hpair0 : Holds x feature_0_1 ∨ Holds x feature_0_4)
    (hpair1 : Holds x feature_1_2 ∨ Holds x feature_1_4)
    (hpair2 : Holds x feature_2_2 ∨ Holds x feature_2_4)
    : False := by
  rcases hpair0 with h0_1 | h0_4
  · rcases hpair2 with h2_2 | h2_4
    · exact leaf_0_infeasible x hbox hbase h0_1 h2_2
    · rcases hpair1 with h1_2 | h1_4
      · exact leaf_1_infeasible x hbox hbase h0_1 h2_4 h1_2
      · exact leaf_2_infeasible x hbox hbase h0_1 h2_4 h1_4
  · rcases hpair1 with h1_2 | h1_4
    · exact leaf_3_infeasible x hbox hbase h0_4 h1_2
    · rcases hpair2 with h2_2 | h2_4
      · exact leaf_4_infeasible x hbox hbase h0_4 h1_4 h2_2
      · exact leaf_5_infeasible x hbox hbase h0_4 h1_4 h2_4

#print axioms selectedTerminalInfeasible

end
end SixTrianglePilot.Selected
