#!/usr/bin/env python3
"""Generate kernel-checked finite radial certificates for the two core pairs.

The Python computations only propose rational data and Lean proof scripts.
The radial and geometric conclusions are Lean theorems, not Python premises.
"""
from __future__ import annotations

import argparse
from fractions import Fraction as F
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SELECTED_SHA256 = "ead5365209d5cc2e91123b15b1be251293ad9a1cdc240b39cad73d8a775a00ff"
ENDPOINTS = ((0, 1), (0, 2), (1, 2), (1, 0), (2, 0), (2, 1))


def require(condition, message):
    if not condition:
        raise ValueError(message)


def q(value):
    value = F(value)
    if value.denominator == 1:
        return f"({value.numerator} : ℝ)"
    return f"({value.numerator} / {value.denominator} : ℝ)"


def vector(values):
    return "![" + ", ".join(q(x) for x in values) + "]"


def lin(normal, variable="d"):
    return f"{q(normal[0])} * {variable} 0 + {q(normal[1])} * {variable} 1"


def reconstruct():
    source = ROOT / "data/selected-terminal.json"
    require(hashlib.sha256(source.read_bytes()).hexdigest() == SELECTED_SHA256,
            "selected terminal hash mismatch")
    selected = json.loads(source.read_text())
    core_data_path = ROOT / "data/core-geometry.json"
    core_data = json.loads(core_data_path.read_text())
    cores = [tuple(tuple(F(x) for x in p) for p in c["vertices"]) for c in core_data["cores"]]
    records = []
    for pair, aindex, bindex, name in ((0, 0, 0, "00"), (1, 0, 2, "02")):
        a, b = cores[aindex], cores[bindex]
        facets = selected["pair_features"][pair]["features"]
        normals = [tuple(F(x) for x in f["raw_normal"]) for f in facets]
        thresholds = [F(f["raw_threshold"]) for f in facets]
        endpoints = [tuple(a[i][axis]-b[j][axis] for axis in (0, 1)) for i, j in ENDPOINTS]
        edge_records = []
        for k, (normal, threshold) in enumerate(zip(normals, thresholds)):
            require(threshold > 0, "nonpositive threshold")
            values = [sum(n*x for n, x in zip(normal, p)) for p in endpoints]
            require(all(x <= threshold for x in values), "invalid facet support")
            require([i for i, x in enumerate(values) if x == threshold] == sorted((k, (k+1)%6)),
                    "facet endpoint incidence mismatch")
            for av in a:
                for bv in b:
                    require(sum(n*(x-y) for n, x, y in zip(normal, av, bv)) <= threshold,
                            "a vertex difference violates its facet")
            start, end = endpoints[k], endpoints[(k+1)%6]
            axis = max((0, 1), key=lambda axis: abs(end[axis]-start[axis]))
            delta = end[axis]-start[axis]
            require(delta != 0, "degenerate edge")
            edge_records.append({"facet": k, "start_indices": ENDPOINTS[k],
                                 "end_indices": ENDPOINTS[(k+1)%6], "axis": axis,
                                 "lambda_coefficient": str(1/delta),
                                 "lambda_constant": str(-start[axis]/delta)})
        records.append({"name": name, "core_indices": [aindex, bindex],
                        "normals": [[str(x) for x in n] for n in normals],
                        "thresholds": [str(h) for h in thresholds], "edges": edge_records})
    return {"format": "six-triangle-radial-certificates-v1",
            "selected_terminal_sha256": SELECTED_SHA256,
            "core_geometry_sha256": hashlib.sha256(core_data_path.read_bytes()).hexdigest(),
            "pairs": records}, selected, cores


def generate(data, selected, cores):
    lines = ["-- Generated by generate_core_facets.py; every certificate field is proved in Lean.",
             "import Pilot.Radial", "import Pilot.CoreData", "import Pilot.SelectedGeometry", "", "set_option maxRecDepth 4096",
             "set_option maxHeartbeats 2000000", "", "namespace SixTrianglePilot.CoreSeparation",
             "noncomputable section", "open CoreData Selected Polygon Geometry", ""]
    for record in data["pairs"]:
        name = record["name"]
        ai, bi = record["core_indices"]
        normals = [[F(x) for x in n] for n in record["normals"]]
        thresholds = list(map(F, record["thresholds"]))
        lines += [f"def normals{name} : Fin 6 → Fin 2 → ℝ := ![" +
                  ", ".join(vector(n) for n in normals) + "]",
                  f"def thresholds{name} : Fin 6 → ℝ := {vector(thresholds)}", "",
                  f"def certificate{name} : RadialCertificate core{ai} core{bi} where",
                  f"  normal := normals{name}", f"  threshold := thresholds{name}",
                  "  threshold_pos k := by", f"    fin_cases k <;> norm_num [thresholds{name}]",
                  "  positive_support d hd := by", "    by_contra! h",
                  "    have h1 := h 1", "    have h3 := h 3", "    have h5 := h 5",
                  "    simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at h1 h3 h5"]
        for i in (1, 3, 5):
            lines.append(f"    change {lin(normals[i])} ≤ 0 at h{i}")
        lines += ["    have hx : d 0 = 0 := by apply le_antisymm <;> linarith",
                  "    have hy : d 1 = 0 := by apply le_antisymm <;> linarith",
                  "    apply hd", "    ext i", "    fin_cases i", "    · exact hx", "    · exact hy",
                  "  boundary_decomposition k d heq hall := by", "    fin_cases k"]
        for edge in record["edges"]:
            k = edge["facet"]
            prev, nxt = (k-1)%6, (k+1)%6
            a0, b0 = edge["start_indices"]
            a1, b1 = edge["end_indices"]
            t = f"{q(edge['lambda_coefficient'])} * d {edge['axis']} + {q(edge['lambda_constant'])}"
            lines += [f"    · have hp := hall {prev}", f"      have hn := hall {nxt}",
                      "      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at heq hp hn",
                      f"      change {lin(normals[k])} = {q(thresholds[k])} at heq",
                      f"      change {lin(normals[prev])} ≤ {q(thresholds[prev])} at hp",
                      f"      change {lin(normals[nxt])} ≤ {q(thresholds[nxt])} at hn",
                      f"      let t : ℝ := {t}",
                      "      have ht0 : 0 ≤ t := by dsimp [t]; linarith",
                      "      have ht1 : t ≤ 1 := by dsimp [t]; linarith",
                      f"      refine ⟨(1-t) • core{ai} {a0} + t • core{ai} {a1}, ?_,",
                      f"        (1-t) • core{bi} {b0} + t • core{bi} {b1}, ?_, ?_⟩"]
            for index, v0, v1 in ((ai, a0, a1), (bi, b0, b1)):
                lines += [f"      · exact (convex_convexHull ℝ (Set.range core{index}))",
                          f"          (subset_convexHull ℝ _ ⟨{v0}, rfl⟩)",
                          f"          (subset_convexHull ℝ _ ⟨{v1}, rfl⟩)",
                          "          (by linarith) ht0 (by ring)"]
            lines += ["      · ext axis", "        fin_cases axis"]
            for axis in (0, 1):
                x0, x1 = cores[ai][a0][axis], cores[ai][a1][axis]
                y0, y1 = cores[bi][b0][axis], cores[bi][b1][axis]
                lines += [f"        · change d {axis} = ((1-t)*{q(x0)} + t*{q(x1)}) -",
                          f"            ((1-t)*{q(y0)} + t*{q(y1)})",
                          "          dsimp [t]", "          linarith"]
        lines += ["", f"#print axioms certificate{name}", ""]
    for pair, (left, right), name in ((0, ("p", "q"), "00"),
                                     (1, ("p", "r"), "02"),
                                     (2, ("q", "r"), "02")):
        records = selected["pair_features"][pair]["features"]
        lines += [f"theorem feature{pair}_iff (p q r : Fin 2 → ℝ) (k : Fin 6) :",
                  f"    Holds (join3 p q r) (features{pair} k) ↔",
                  f"      thresholds{name} k ≤ linear (normals{name} k) ({right} - {left}) := by",
                  "  fin_cases k"]
        for feature in records:
            row = feature["row"]
            coefficients = list(map(F, row["coefficients"]))
            rhs = F(row["rhs"])
            normal = list(map(F, feature["raw_normal"]))
            threshold = F(feature["raw_threshold"])
            terms = [f"{q(c)} * {v} {axis}" for c, (v, axis) in
                     zip(coefficients, (("p", 0), ("p", 1), ("q", 0), ("q", 1), ("r", 0), ("r", 1)))]
            lines += ["  · simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]",
                      f"    change {q(rhs)} ≤ " + " + (".join(terms) + ")"*5 + " ↔",
                      f"      {q(threshold)} ≤ {q(normal[0])} * ({right} 0 - {left} 0) +",
                      f"        {q(normal[1])} * ({right} 1 - {left} 1)",
                      "    constructor <;> intro h <;> linarith only [h]"]
        lines += [""]
    lines += ["end", "end SixTrianglePilot.CoreSeparation", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data, selected, cores = reconstruct()
    outputs = {ROOT / "Pilot/CoreFacets.lean": generate(data, selected, cores),
               ROOT / "data/core-facets.json": json.dumps(data, indent=2)+"\n"}
    for path, content in outputs.items():
        if args.check:
            require(path.is_file() and path.read_bytes() == content.encode(),
                    f"generated output differs: {path.name}")
        else:
            path.write_text(content)
    print("RADIAL_CERTIFICATES_REGENERATED" if args.check else "RADIAL_CERTIFICATES_WRITTEN")


if __name__ == "__main__":
    main()
