#!/usr/bin/env python3
"""Generate the exact polygon-to-linear bridge from the unchanged pilot data.

All vertex inequalities emitted by this generator are proved again inside Lean.
Python minima and maxima are proposals for those proofs, not trusted premises.
"""
from __future__ import annotations

import argparse
from fractions import Fraction as F
import hashlib
import json
from pathlib import Path

from extract import qlean, vector, require, sha

ROOT = Path(__file__).resolve().parent
DATA_HASH = "ead5365209d5cc2e91123b15b1be251293ad9a1cdc240b39cad73d8a775a00ff"
SELECTED_HASH = "01d89c301075e7d22f4e7e5559e1784ebd339b7224ead2fdd86c69795c39e8ce"


def bounds(row, polygons):
    coefficients = list(map(F, row["coefficients"]))
    values = [[sum(coefficients[2 * pose + axis] * F(point[axis]) for axis in (0, 1))
               for point in polygon] for pose, polygon in enumerate(polygons)]
    return [min(v) for v in values], [max(v) for v in values]


def assumptions():
    return [
        "    (p q r : Fin 2 → ℝ)",
        "    (hp : p ∈ convexHull ℝ (Set.range vertices0))",
        "    (hq : q ∈ convexHull ℝ (Set.range vertices1))",
        "    (hr : r ∈ convexHull ℝ (Set.range vertices2))",
    ]


def bound_proof(row_name, row, polygons, extrema, direction):
    lemma = "linear_ge_on_product_hulls" if direction == "lower" else "linear_le_on_product_hulls"
    result = [
        f"  have hbound := {lemma} vertices0 vertices1 vertices2 p q r hp hq hr",
        f"    {row_name}.a " + " ".join(qlean(x) for x in extrema),
    ]
    for pose in range(3):
        c0, c1 = row["coefficients"][2 * pose:2 * pose + 2]
        result.extend([
            "    (by",
            "      intro i",
            "      simp only [linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]",
        ])
        if F(c0) == F(c1) == 0:
            zero_form = f"(0 : ℝ) * (vertices{pose} i) 0 + (0 : ℝ) * (vertices{pose} i) 1"
            condition = f"(0 : ℝ) ≤ {zero_form}" if direction == "lower" else f"{zero_form} ≤ (0 : ℝ)"
            result.extend(["      change " + condition,
                           "      simp only [zero_mul, add_zero, le_refl])"])
        else:
            result.append("      fin_cases i")
            for index, point in enumerate(polygons[pose]):
                expression = f"{qlean(c0)} * {qlean(point[0])} + {qlean(c1)} * {qlean(point[1])}"
                condition = f"{qlean(extrema[pose])} ≤ {expression}" if direction == "lower" else f"{expression} ≤ {qlean(extrema[pose])}"
                result.append("      · change " + condition)
                result.append("        norm_num1" + (")" if index == len(polygons[pose]) - 1 else ""))
    return result


def right_sum(terms):
    return terms[0] if len(terms) == 1 else terms[0] + " + (" + right_sum(terms[1:]) + ")"


def generate(data):
    require(len(data["base_rows"]) == 34, "unexpected base row count")
    require([len(p) for p in data["polygons"]] == [8, 8, 6], "unexpected polygons")
    require([p["retained_features"] for p in data["pair_features"]] == [[1, 4], [2, 4], [2, 4]],
            "unexpected retained features")
    output = [
        "-- Generated by generate_geometry.py from unchanged selected-terminal.json.",
        f"-- Input data SHA-256: {DATA_HASH}",
        "-- Original certificate outer path: 0000000001.",
        "-- The conclusion is conditional on full explicit feature disjunctions, not triangle packability.",
        "import Pilot.Polygon", "import Pilot.Selected", "import Mathlib.Tactic.Linarith", "",
        "set_option maxRecDepth 4096", "set_option maxHeartbeats 2000000", "",
        "namespace SixTrianglePilot.Geometry", "noncomputable section",
        "open SixTrianglePilot.Selected SixTrianglePilot.Polygon", "",
    ]
    for i, polygon in enumerate(data["polygons"]):
        output.append(f"def vertices{i} : Fin {len(polygon)} → Fin 2 → ℝ := ![" +
                      ", ".join(vector(p) for p in polygon) + "]")
    output.append("")
    for pair in data["pair_features"]:
        require(len(pair["features"]) == 6, "expected every original feature")
        names = []
        for feature in pair["features"]:
            p, f = pair["pair"], feature["feature"]
            if feature["retained"]:
                names.append(f"feature_{p}_{f}")
            else:
                name = f"omitted_{p}_{f}"
                row = feature["row"]
                names.append(name)
                output.append(f"def {name} : Constraint := ⟨{vector(row['coefficients'])}, {qlean(row['rhs'])}⟩")
        output.append(f"def features{pair['pair']} : Fin 6 → Constraint := ![" + ", ".join(names) + "]")
    output.extend([
        "def allFeatures : Fin 3 → Fin 6 → Constraint := ![features0, features1, features2]", "",
        "/-- The full unfiltered weak disjunction: one of all six listed features per pair. -/",
        "def FullSeparation (x : Fin 6 → ℝ) : Prop :=",
        "  ∀ pair : Fin 3, ∃ feature : Fin 6, Holds x (allFeatures pair feature)", "",
    ])
    base_records = []
    for i, row in enumerate(data["base_rows"]):
        lower, _ = bounds(row, data["polygons"])
        require(sum(lower) >= F(row["rhs"]), "base row not valid on polygon product")
        base_records.append({"base_row": i, "block_minima": list(map(str, lower)),
                             "minimum_minus_rhs": str(sum(lower) - F(row["rhs"]))})
        name = f"base_{i}"
        output.append(f"theorem baseRow_{i}_from_hulls")
        output.extend(assumptions())
        output.append(f"    : Holds (join3 p q r) {name} := by")
        output.extend(bound_proof(name, row, data["polygons"], lower, "lower"))
        output.extend([
            f"  have htarget : {name}.b ≤ " + " + ".join(qlean(x) for x in lower) + " := by",
            f"    norm_num only [{name}]",
            "  exact le_trans htarget hbound", "",
        ])
    output.append("theorem baseRows_from_hulls")
    output.extend(assumptions())
    output.extend([
        "    : ∀ i : Fin 34, Holds (join3 p q r) (baseRows i) := by",
        "  intro i; fin_cases i",
    ])
    for i in range(34):
        output.append(f"  · exact baseRow_{i}_from_hulls p q r hp hq hr")
    output.extend([
        "",
        "/-- Coordinate bounds follow from twelve of the now-proved base rows. -/",
        "theorem coordinateBounds_of_base (x : Fin 6 → ℝ)",
        "    (hbase : ∀ i : Fin 34, Holds x (baseRows i)) : InBox x := by",
        "  constructor",
    ])
    for direction, indices in (("lower", [0, 2, 12, 14, 24, 26]),
                               ("upper", [1, 3, 13, 15, 25, 27])):
        output.append("  · intro j; fin_cases j")
        for coordinate, i in enumerate(indices):
            row = data["base_rows"][i]
            output.append(f"    · have h := hbase ({i} : Fin 34)")
            output.append("      simp only [Holds, linear, Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero] at h")
            expression = right_sum([f"{qlean(c)} * x {j}" for j, c in enumerate(row["coefficients"])])
            output.append(f"      change {qlean(row['rhs'])} ≤ {expression} at h")
            simplifiers = ["zero_mul", "one_mul" if direction == "lower" else "neg_one_mul"]
            if coordinate < 5:
                simplifiers.append("add_zero")
            if coordinate > 0:
                simplifiers.append("zero_add")
            output.append("      simp only [" + ", ".join(simplifiers) + "] at h")
            bound = data["coordinate_bounds"][coordinate][0 if direction == "lower" else 1]
            output.append("      change " + (f"{qlean(bound)} ≤ x {coordinate}" if direction == "lower"
                                               else f"x {coordinate} ≤ {qlean(bound)}"))
            output.append("      linarith only [h]")
    output.extend(["", "theorem coordinateBounds_from_hulls"])
    output.extend(assumptions())
    output.extend([
        "    : InBox (join3 p q r) := by",
        "  exact coordinateBounds_of_base _ (baseRows_from_hulls p q r hp hq hr)", "",
    ])
    omitted_records = []
    for pair in data["pair_features"]:
        for feature in pair["features"]:
            if feature["retained"]:
                continue
            p, f = pair["pair"], feature["feature"]
            row = feature["row"]
            _, upper = bounds(row, data["polygons"])
            gap = F(row["rhs"]) - sum(upper)
            require(gap > 0, "omitted feature lacks strict normalized gap")
            omitted_records.append({"pair": p, "feature": f, "block_maxima": list(map(str, upper)),
                                    "rhs_minus_maximum": str(gap)})
            name = f"omitted_{p}_{f}"
            output.append(f"theorem {name}_impossible")
            output.extend(assumptions())
            output.append(f"    : ¬ Holds (join3 p q r) {name} := by")
            output.append("  intro hfeature")
            output.extend(bound_proof(name, row, data["polygons"], upper, "upper"))
            output.extend([
                "  have hgap : " + " + ".join(qlean(x) for x in upper) + f" < {name}.b := by",
                f"    norm_num only [{name}]",
                "  exact (not_le_of_gt hgap) (le_trans hfeature hbound)", "",
            ])
    for pair in data["pair_features"]:
        p = pair["pair"]
        kept = pair["retained_features"]
        output.append(f"theorem retained_{p}_of_full")
        output.extend(assumptions())
        output.append(f"    (hfull : ∃ f : Fin 6, Holds (join3 p q r) (features{p} f))")
        output.append("    : " + " ∨ ".join(f"Holds (join3 p q r) feature_{p}_{f}" for f in kept) + " := by")
        output.extend(["  rcases hfull with ⟨f, hf⟩", "  fin_cases f"])
        for feature in pair["features"]:
            f = feature["feature"]
            if feature["retained"]:
                output.append(f"  · exact Or.{'inl' if f == kept[0] else 'inr'} hf")
            else:
                output.append(f"  · exact False.elim (omitted_{p}_{f}_impossible p q r hp hq hr hf)")
        output.append("")
    output.extend([
        "/-- Stronger conditional theorem: actual convex-hull membership and the full",
        "six-feature weak disjunctions imply contradiction. No box bounds, base rows,",
        "or filtering decisions are hypotheses. Triangle-packability is not asserted. -/",
        "theorem polygonTerminalInfeasible",
    ])
    output.extend(assumptions())
    output.extend([
        "    (hseparation : FullSeparation (join3 p q r)) : False := by",
        "  exact selectedTerminalInfeasible (join3 p q r)",
        "    (coordinateBounds_from_hulls p q r hp hq hr)",
        "    (baseRows_from_hulls p q r hp hq hr)",
        "    (retained_0_of_full p q r hp hq hr (hseparation 0))",
        "    (retained_1_of_full p q r hp hq hr (hseparation 1))",
        "    (retained_2_of_full p q r hp hq hr (hseparation 2))", "",
        "#print axioms baseRows_from_hulls",
        "#print axioms coordinateBounds_from_hulls",
        "#print axioms omitted_0_0_impossible",
        "#print axioms retained_0_of_full",
        "#print axioms retained_1_of_full",
        "#print axioms retained_2_of_full",
        "#print axioms polygonTerminalInfeasible", "", "end", "end SixTrianglePilot.Geometry", "",
    ])
    metadata = {
        "format": "six-triangle-polygon-bridge-v1",
        "scope": "Actual Mathlib convex hulls and all six listed weak features per pair imply contradiction for one fixed cell. The triangle-to-features and global/local arguments remain unformalized.",
        "certificate_sha256": data["source"]["certificate_sha256"],
        "outer_path": data["source"]["outer_path"],
        "input_sha256": {"data/selected-terminal.json": DATA_HASH, "Pilot/Selected.lean": SELECTED_HASH},
        "polygon_vertex_counts": list(map(len, data["polygons"])),
        "base_row_bounds": base_records, "omitted_feature_bounds": omitted_records,
        "all_feature_counts": [6, 6, 6], "retained_feature_counts": [2, 2, 2],
        "mutation": {"row": "omitted_0_0", "changed_rhs": "0",
                     "vertex_indices": [0, 0, 0], "linear_value_at_witness": "0",
                     "reason": "The first vertices of polygons 0 and 1 coincide, so equality satisfies the mutated weak inequality. A strict exclusion would be false."},
    }
    # Independently confirm that the intended negative test reaches legal equality.
    mutated_row = data["pair_features"][0]["features"][0]["row"]
    witness = [F(x) for polygon in data["polygons"] for x in polygon[0]]
    require(sum(F(a) * x for a, x in zip(mutated_row["coefficients"], witness)) == 0,
            "mutation equality witness mismatch")
    return "\n".join(output), metadata


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check deterministic regeneration without writing")
    args = parser.parse_args()
    require(sha(ROOT / "data/selected-terminal.json") == DATA_HASH, "frozen input data hash mismatch")
    require(sha(ROOT / "Pilot/Selected.lean") == SELECTED_HASH, "frozen selected theorem hash mismatch")
    data = json.loads((ROOT / "data/selected-terminal.json").read_text())
    lean, metadata = generate(data)
    outputs = {ROOT / "Pilot/SelectedGeometry.lean": lean,
               ROOT / "data/polygon-bridge.json": json.dumps(metadata, indent=2, sort_keys=True) + "\n"}
    for path, contents in outputs.items():
        if args.check:
            require(path.read_text() == contents, f"regeneration mismatch: {path.name}")
        else:
            path.write_text(contents)
    print(json.dumps({"status": "POLYGON_BRIDGE_REPRODUCED" if args.check else "POLYGON_BRIDGE_GENERATED",
                      "sha256": {str(p.relative_to(ROOT)): sha(p) for p in outputs}}, indent=2))


if __name__ == "__main__":
    main()
