#!/usr/bin/env python3
"""Reconstruct the selected rational cores; Lean checks their geometric use.

This generator proposes constants, never a proof premise.  It independently
reconstructs the rational formulas and checks agreement with the frozen exact
consumer.  The resulting Lean module contains definitions only.
"""
from __future__ import annotations

import argparse
from fractions import Fraction as F
import hashlib
import importlib.util
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent
SELECTED_SHA256 = "ead5365209d5cc2e91123b15b1be251293ad9a1cdc240b39cad73d8a775a00ff"
CONSUMER_SHA256 = "8da01b96db32d0726138650e66132862f241228ca3b9340c7841ef5ec819905a"


def require(condition, message):
    if not condition:
        raise ValueError(message)


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def coefficients(t):
    denominator = 1 + 3*t*t
    return (1-3*t*t)/denominator, 2*t/denominator


def rotate(q, t):
    c, b = coefficients(t)
    return ((c-b)*q[0]-2*b*q[1], 2*b*q[0]+(c+b)*q[1])


def reconstruct(public_root):
    source = ROOT / "data/selected-terminal.json"
    consumer = public_root / "verification/independent_global.py"
    require(digest(source) == SELECTED_SHA256, "selected terminal hash mismatch")
    require(digest(consumer) == CONSUMER_SHA256, "frozen consumer hash mismatch")
    selected = json.loads(source.read_text())
    sys.dont_write_bytecode = True
    spec = importlib.util.spec_from_file_location("frozen_core_consumer", consumer)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    reference = ((F(-1,3), F(-1,3)), (F(2,3), F(-1,3)), (F(-1,3), F(2,3)))
    records = []
    for index, interval in enumerate(selected["outer_box"][2::3]):
        lo, hi = map(F, interval)
        frame = (lo+hi)/2
        rel = [(t-frame)/(1+3*t*frame) for t in (lo, hi)]
        support = [c+3*abs(b) for c, b in map(coefficients, rel)]
        if any(rel[0] <= critical <= rel[1] for critical in (F(-1,3), F(1,3))):
            support.append(F(2))
        scale = 1/max(support)
        vertices = tuple(tuple(scale*x for x in rotate(q, frame)) for q in reference)
        require(vertices == module.oriented_core((lo, hi)), "independent core reconstruction mismatch")
        records.append({"index": index, "interval": [str(lo), str(hi)],
                        "frame": str(frame), "scale": str(scale),
                        "vertices": [[str(x) for x in q] for q in vertices]})
    require(records[0]["vertices"] == records[1]["vertices"], "first two cores no longer coincide")
    return {
        "format": "six-triangle-selected-core-data-v1",
        "source": {"selected_terminal_sha256": SELECTED_SHA256,
                   "consumer_sha256": CONSUMER_SHA256,
                   "certificate_sha256": selected["source"]["certificate_sha256"],
                   "outer_path": selected["source"]["outer_path"]},
        "coordinate_convention": "oblique coordinates: Cartesian image is (u+v/2, sqrt(3)*v/2)",
        "reference_vertices": [[str(x) for x in q] for q in reference],
        "cores": records,
    }


def qlean(value):
    q = F(value)
    return f"({q.numerator} : ℝ)" if q.denominator == 1 else f"({q.numerator} / {q.denominator} : ℝ)"


def vector(values):
    return "![" + ", ".join(qlean(x) for x in values) + "]"


def generate(data):
    lines = ["-- Generated by generate_core_data.py from the frozen selected cell.",
             "-- Definitions only: all containment and exclusion claims are proved separately.",
             "import Mathlib.Basic.Real.Basic", "import Mathlib.Data.Fin.VecNotation", "",
             "namespace SixTrianglePilot.CoreData", "noncomputable section", "",
             "def referenceVertices : Fin 3 → Fin 2 → ℝ := ![" +
             ", ".join(vector(q) for q in data["reference_vertices"]) + "]", ""]
    for record in data["cores"]:
        i = record["index"]
        expression = "core0" if i == 1 else "![" + ", ".join(vector(q) for q in record["vertices"]) + "]"
        lines.append(f"def core{i} : Fin 3 → Fin 2 → ℝ := {expression}")
    lines.extend(["", "def core : Fin 3 → Fin 3 → Fin 2 → ℝ := ![core0, core1, core2]"])
    for name, values in (
        ("lower", [r["interval"][0] for r in data["cores"]]),
        ("upper", [r["interval"][1] for r in data["cores"]]),
        ("frames", [r["frame"] for r in data["cores"]]),
        ("scales", [r["scale"] for r in data["cores"]]),
    ):
        lines.append(f"def {name} : Fin 3 → ℝ := {vector(values)}")
    lines.extend(["", "end", "end SixTrianglePilot.CoreData", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--public-root", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = reconstruct(args.public_root.resolve())
    outputs = {ROOT / "Pilot/CoreData.lean": generate(data),
               ROOT / "data/core-geometry.json": json.dumps(data, indent=2)+"\n"}
    for path, content in outputs.items():
        if args.check:
            require(path.is_file() and path.read_bytes() == content.encode(), f"generated output differs: {path.name}")
        else:
            path.write_text(content)
    print("SELECTED_CORE_DATA_REGENERATED" if args.check else "SELECTED_CORE_DATA_WRITTEN")


if __name__ == "__main__":
    main()
